// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EIRhDO0MX7o4Fi-Dy5PPLOItqBKV3bs',
    appId: '1:965276243384:web:3c23e4ca2be85ac2842b4d',
    messagingSenderId: '965276243384',
    projectId: 'tugasakhirsanbercode-55376',
    authDomain: 'tugasakhirsanbercode-55376.firebaseapp.com',
    storageBucket: 'tugasakhirsanbercode-55376.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1jnokWq-QBIjlt6vqHAa2B0VLC9iIDE',
    appId: '1:965276243384:android:7540fa4ff5364337842b4d',
    messagingSenderId: '965276243384',
    projectId: 'tugasakhirsanbercode-55376',
    storageBucket: 'tugasakhirsanbercode-55376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnIwGGVoKSvEjtPGW_vFojTVawXDiN-8c',
    appId: '1:965276243384:ios:d0ebc8b69380f1e8842b4d',
    messagingSenderId: '965276243384',
    projectId: 'tugasakhirsanbercode-55376',
    storageBucket: 'tugasakhirsanbercode-55376.firebasestorage.app',
    iosBundleId: 'com.example.tugasAkhirSanbercode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnIwGGVoKSvEjtPGW_vFojTVawXDiN-8c',
    appId: '1:965276243384:ios:d0ebc8b69380f1e8842b4d',
    messagingSenderId: '965276243384',
    projectId: 'tugasakhirsanbercode-55376',
    storageBucket: 'tugasakhirsanbercode-55376.firebasestorage.app',
    iosBundleId: 'com.example.tugasAkhirSanbercode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2EIRhDO0MX7o4Fi-Dy5PPLOItqBKV3bs',
    appId: '1:965276243384:web:015ce929a29e1b4e842b4d',
    messagingSenderId: '965276243384',
    projectId: 'tugasakhirsanbercode-55376',
    authDomain: 'tugasakhirsanbercode-55376.firebaseapp.com',
    storageBucket: 'tugasakhirsanbercode-55376.firebasestorage.app',
  );
}
